### ISSUE TITLE
Click twice to trigger OnItemClickListener

### ISSUE THREAD

**Issue by jkguang** [johannilsson/android-pulltorefresh#42]
Sorry for my English.
I test the example in the source code, and I found a problem.
Step:
1 Scroll Up until  the first item is visible (Do not show the refreshView)
2 Click any list item, nothing happens (could not trigger OnItemClickListener),  until you click it again.

I hope you understand what i said.
Thank you.

**Comment by johannilsson** [comment]
Hi, could you try the [scrollfix_for_short_list](https://github.com/johannilsson/android-pulltorefresh/tree/scrollfix_for_short_list) branch, I believe this was fixed in that branch too.

**Comment by jkguang** [comment]
Thank you.
But still have that problem.
Scroll down for some positions, and then Scroll up fast until the first item is visible (Do not show the refreshView).
Then click any list item, You will find the problem.
I test in my Moto MB525 (Android 2.3.7)

**Comment by johannilsson** [comment]
Ah, when scrolling fast I can reproduce it too.
